### ISSUE TITLE
where is the paper?

### ISSUE THREAD

**Issue by jlqzzz** [YoushaaMurhij/RVCDet#1]
Hi,
where is the paper?

**Comment by YoushaaMurhij** [comment]
The paper is still under review. I will update the repo after getting the final accept (within a month I think).
Thanks for your interest.

**Comment by YoushaaMurhij** [comment]
Sorry for the delay in publishing the paper. Here is link to a preprint on Arxiv: https://arxiv.org/abs/2301.04058.
Once the paper appears online, I will update the repo.
Thanks for your interest.
